name: Build Test

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/build-test.yml"

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code into the Go module directory
        if: steps.cache-project.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version-file: "./go.mod"
        id: go
      - name: Init Module
        run: |
          go mod tidy && go work vendor
      - name: Init Project
        run: |
          go build -x -a cmd/main.go
          ./main --help
